import './globals.css'
import { Inter } from 'next/font/google'
import type { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

type LayoutProps = {children?: ReactNode}

export const metadata = {
  title: 'Give Me Money',
  description: 'Generated by create next app',
}

export default function RootLayout(props: LayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>{props.children}</body>
    </html>
  )
}
